# Generated by Django 4.2.17 on 2024-12-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
